services:
  db:
    container_name: postgres
    image: postgres:13
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
    - app-db-data:/var/lib/postgresql/data/pgdata

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    restart: always
    volumes:
        - ./backend:/app
    environment:
        - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    environment:
      NEXT_PUBLIC_API_URL: backend:8000
    ports:
      - "3000:3000" 
    restart: always
    volumes:
        - ./frontend:/app
    depends_on:
      - backend

volumes:
  app-db-data: